#!/usr/bin/env zsh

# Expand $PATH
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Setup pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Add Homebrew binaries to PATH
export PATH=$PATH:/opt/homebrew/bin

# Configure brewfile
export HOMEBREW_BUNDLE_FILE=$HOME/.brew

# Make vim the default editor.
export EDITOR='vim';

# Fix GPG signing issue (https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0)
export GPG_TTY=$(tty)

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Set Go exports
export GOPATH=~/go
export GOBIN=~/bin

# Allow multi-threaded apps on Mac
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# Force Packer to use /tmp for cache
export PACKER_CACHE_DIR=/tmp/packer
