#!/usr/bin/env bash

# Add Homebrew binaries to PATH
export PATH=$PATH:/opt/homebrew/bin

# Add Python binaries to PATH
export PATH=$PATH:/Users/josh/Library/Python/3.8/bin

# Make vim the default editor.
export EDITOR='vim';

# Fix GPG signing issue (https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0)
export GPG_TTY=$(tty)

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Set Go exports
export GOPATH=~/go
export GOBIN=~/bin

# Allow multi-threaded apps on Mac
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# Force Packer to use /tmp for cache
export PACKER_CACHE_DIR=/tmp/packer

# Remove bash deprecation warning
export BASH_SILENCE_DEPRECATION_WARNING=1
